import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><div className="min-h-screen flex flex-col">
      <div className="bg-blue-600 text-white py-4">
        <nav className="container mx-auto flex justify-between">
          <Link className="text-lg font-bold" href="/">
            MyApp
          </Link>
          <div>
            <Link className="mr-4" href="/auth/login">
              Login
            </Link>
            <Link href="/auth/register">
              Register
            </Link>
          </div>
        </nav>
      </div>
      <main className="flex-grow container mx-auto py-8">
        {children}
      </main>
      <footer className="bg-gray-800 text-white py-4">
        <div className="container mx-auto text-center">
          &copy; 2024 MyApp. All rights reserved.
        </div>
      </footer>
    </div></body>
    </html>
  );
}
